"""deviceinfo

Revision ID: 7cd18d1eb473
Revises: 42ff4a6b863c
Create Date: 2024-07-15 22:50:03.201266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd18d1eb473'
down_revision = '42ff4a6b863c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deviceinfo', schema=None) as batch_op:
        batch_op.drop_index('phonenumber')
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deviceinfo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('phonenumber', ['phonenumber'], unique=True)

    # ### end Alembic commands ###
